#!/usr/bin/env python3
"""
Example usage of step6_add_chunk_references.py

This script demonstrates how to use the step6 module to add chunk references
to fiscal notes generated by step5.
"""

import os
import sys
from step6_add_chunk_references import add_chunk_references_to_fiscal_notes

def main():
    """
    Example usage of step6 to add chunk references to fiscal notes.
    """
    # Example paths - adjust these to your actual paths
    base_dir = "/Users/rodericktabalba/Documents/GitHub/financial-rag/src/fiscal_notes/generation/HB_400_2025"  # e.g., "/Users/username/bills/HB1234_2025"
    
    fiscal_notes_dir = os.path.join(base_dir, "fiscal_notes")
    documents_dir = os.path.join(base_dir, "documents")
    
    print("🚀 Step 6: Adding Chunk References to Fiscal Notes")
    print("=" * 60)
    print(f"📁 Fiscal Notes Directory: {fiscal_notes_dir}")
    print(f"📄 Documents Directory: {documents_dir}")
    print()
    
    # Check if directories exist
    if not os.path.exists(fiscal_notes_dir):
        print(f"❌ Error: Fiscal notes directory not found: {fiscal_notes_dir}")
        print("💡 Make sure you've run step5 first to generate fiscal notes.")
        return 1
    
    if not os.path.exists(documents_dir):
        print(f"❌ Error: Documents directory not found: {documents_dir}")
        print("💡 Make sure you've run step3 first to retrieve documents.")
        return 1
    
    try:
        # Process fiscal notes to add chunk references
        enhanced_dir = add_chunk_references_to_fiscal_notes(fiscal_notes_dir, documents_dir)
        
        print()
        print("✅ SUCCESS!")
        print(f"📁 Enhanced fiscal notes saved to: {enhanced_dir}")
        print()
        print("📋 What was added:")
        print("   • Document sentences (individual sentences for precision)")
        print("   • AllMiniLM embedding-based similarity matching")
        print("   • Sentence-level references for each citation")
        print("   • Similarity scores for reference quality")
        print()
        print("🔄 Next steps:")
        print("   • The enhanced fiscal notes now include chunk references")
        print("   • Citations will show the source text they reference")
        print("   • Similarity scores indicate reference quality")
        print("   • Use these enhanced notes in your application")
        
        return 0
        
    except Exception as e:
        print(f"❌ Error processing fiscal notes: {e}")
        return 1

if __name__ == "__main__":
    sys.exit(main())
